### ISSUE TITLE
API rate limit of 60 exceeded

### ISSUE THREAD

**Issue by dpordomingo** [src-d/docsrv#11]
Performing only one request in local, I got many of these:
```
ERRO[0039] GET https://api.github.com/repos//local/releases?page=1&per_page=100: 404 Not Found []  owner= project=local version=404.html
```
Then, this one:
```
ERRO[0039] GET https://api.github.com/repos//local/releases?page=1&per_page=100: 403 API rate limit exceeded for 77.228.105.51. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.); rate reset in 59m53.684667263s  owner= project=local version=404.html
```
And then maaaaaaany of these
```
ERRO[0039] GET https://api.github.com/repos//local/releases?page=1&per_page=100: 403 API rate limit of 60 still exceeded until 2017-05-30 07:59:23 +0200 CEST, not making remote request.; rate reset in 59m53.666557389s  owner= project=local version=404.html
```

In order to avoid reaching the api limit, it should be implemented any kind of protection, throttle... idk

**Comment by erizocosmico** [comment]
That's because you are unauthenticated. If you add the `GITHUB_API_KEY` environment variable you won't get that.

In a real production env this should not happen at all. Versions are cached, and latest version is checked 1 time every hour, so you should never get a rate limit (as long as you provide such API key).

**Comment by dpordomingo** [comment]
What if you spam with:
```
let version = 1
http.req('http://go-git.sourced.tech/'+version)
version++
```
It will consume our [quota](https://developer.github.com/v3/#rate-limiting), won't it?

**Comment by erizocosmico** [comment]
That is actually right. Ok, I think we can do the following:

We already have all the versions cached (because of the versions.json endpoint) so instead of updating it every now and then we can periodically update them every let's say 5 minutes and always check from there without doing any requests at all.

What do you think?

EDIT: no, we can't. We don't have beforehand all the projects that will be served (which are the ones defined in the `mappings.yml` + all available in GitHub for `GITHUB_ORG`).

**Comment by dpordomingo** [comment]
as discussed irl, it can be done "per known (already visited/installed) project"... so yes, I like it !!

**Comment by dpordomingo** [comment]
as discussed irl, it can be done "per known (already visited/installed) project"...
so yes, I like it !!

**Comment by erizocosmico** [comment]
This can be closed for now.

**Comment by dpordomingo** [comment]
kind of solved by https://github.com/src-d/docsrv/pull/14

**Comment by erizocosmico** [comment]
I have doubts it solves much if docsrv is running without a token, though. But with a token it _should_ be enough.
